Change python2.7 to python in unix_build.sh
We are using pyrf in the wbia docker image which uses python 3.6 so we
need to change `unix_build.sh`.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named utool
```